config/routes.rb
Rails.application.routes.draw do
  get 'streamer/show'
  resources :requests
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "requests#index"

  get '/requests/:id/tocar', to: 'requests#tocar', as: 'tocar_request'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/video_embed_url_generator.rb
class VideoEmbedUrlGenerator
  REGEX_ID = %r{(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/|vimeo\.com\/)([a-zA-Z0-9_-]{8,11})}.freeze
  REGEX_PROVIDER = /(youtube|youtu\.be|vimeo)/.freeze

  def initialize(url)
    @url = url
  end

  def construct_iframe
    '<iframe '\
      'width="640" '\
      'height="480" '\
      'frameborder="0" '\
      'allow="autoplay; fullscreen" '\
      'allowfullscreen, '\
      "src='#{construct_url}'>"\
    '</iframe>'
  end

  def construct_url
    case video_provider
    when :youtube
      "https://www.youtube.com/embed/#{video_id}"
    when :vimeo
      "https://player.vimeo.com/video/#{video_id}"
    end
  end

  private

  attr_accessor :url

  def video_provider
    case matched_result(REGEX_PROVIDER)
    when 'youtube', 'youtu.be'
      :youtube
    when 'vimeo'
      :vimeo
    end
  end

  def video_id
    matched_result(REGEX_ID)
  end

  def matched_result(regex)
    match = regex.match(url)
    return if match.blank? || match[1].blank?

    match[1]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy tocar ]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  def tocar
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to request_url(@request), notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to request_url(@request), notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:link)
    end
end

app/controllers/streamer_controller.rb
class StreamerController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/streamer_helper.rb
module StreamerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songrequest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/_request.html.erb
<div id="<%= dom_id request %>">
  <p>
    <strong>Link:</strong>
    <%= request.link %>
  </p>

</div>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Show this request", @request %> |
  <%= link_to "Back to requests", requests_path %>
</div>

app/views/requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Requests</h1>

<div id="requests">
  <% @requests.each do |request| %>
    <%= render request %>
    <p>
      <%= link_to "Show this request", request %>
    </p>
  <% end %>
</div>

<%= link_to "New request", new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Back to requests", requests_path %>
</div>

app/views/requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @request %>

<div>
  <%# <%= link_to "Edit this request", edit_request_path(@request) %> |
  <%= link_to "Back to requests", requests_path %>

  <%# <%= button_to "Destroy this request", @request, method: :delete %>
</div>

app/views/requests/tocar.html.erb
<%= turbo_frame_tag @request, "player" do %>
  <%== VideoEmbedUrlGenerator.new(@request.link).construct_iframe %>
<% end %>

app/views/streamer/show.html.erb
<h1>streamer constroller</h1>

<p> requests: </p>
<% Request.all.each do |r| %>
  <%= r.link %>
  <%= button_to "Destroy this request", r, method: :delete %>

  <%= turbo_frame_tag r, "player" do %>
    <%= link_to "tocar", tocar_request_path(r) %>
  <% end %>
  <%# <%== VideoEmbedUrlGenerator.new(r.link).construct_iframe %>
  <br>
<% end %>